services:
  otp-bot:
    build: .
    container_name: tg-mentoring-otp-bot-py
    restart: unless-stopped
    ports:
      - "127.0.0.1:8011:8011"
    env_file:
      - deploy/config.env
      - ~/common-config/config.env
